- hosts: all
  gather_facts: False
  tasks:
    - name: get python2
      stat:
        path: /usr/bin/python
      ignore_errors: yes
      register: python2_exist

    - name: install python2
      raw: apt-get -y install python-simplejson
      ignore_errors: yes
      when: python2_exist.failed == true

    # - name: gather and delegate facts
    #   setup:
    #   delegate_to: "{{ item }}"
    #   delegate_facts: True
    #   loop: "{{ query('inventory_hostnames', 'all') }}"
    #   run_once: true

- hosts: all
  roles:
    - ceph-common

- hosts: ceph-mon
  roles:
    - ceph-mon
#     - ceph-osd
#
# - hosts: ceph-osd
#   roles:
#     - ceph-osd
