- hosts: all
    vars:
      delegate_facts_host: True

    tasks:
      - name: check for python2
        stat:
          path: /usr/bin/python
        ignore_errors: yes
        register: systempython2

      - name: install python2 for debian based systems
        raw: sudo apt-get -y install python-simplejson
        ignore_errors: yes
        when:
          - systempython2.stat.exists is undefined or systempython2.stat.exists == false

    - name: gather facts
      setup:
      when:
        - not delegate_facts_host | bool

    - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items: "{{ groups['all'] }}"
      run_once: true
      when:
        - delegate_facts_host | bool

- hosts: all
  roles:
    - ceph-common

- hosts: ceph-mon
  roles:
    - ceph-mon
    - ceph-osd

- hosts: ceph-osd
  roles:
    - ceph-osd
