- name: change hostname
  hostname:
    name: "{{ hostname }}"

- name: copy /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: gather facts
  setup:


# - name: persistent hostname
#   replace:
#     path: /etc/hostname
#     regexp: '*'
#     replace: "{{ hostname }}"

# - name: debug hostname
#   debug:
#     msg: "{{ hostname }}"
