---
- name: copy ceph.conf.j2
  template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    group: ceph
    owner: ceph
    mode: "0600"

- name: stat keyring file
  stat:
    path: /var/lib/ceph/tmp/ceph.mon..keyring
  register: keyring_tmp

- name: create monitor initial keyring
  ceph_key:
    name: mon.
    state: present
    dest: "/var/lib/ceph/tmp/"
    secret: "{{ ceph.monitor_keyring }}"
    cluster: "{{ ceph.cluster_name }}"
    caps:
      mon: allow *
    import_key: False
  register: keyring_tmp_create
  when: keyring_tmp.stat.exists == false

- name: set initial monitor key permissions
  file:
    path: "/var/lib/ceph/tmp/{{ ceph.cluster_name }}.mon..keyring"
    owner: "ceph"
    group: "ceph"
    mode: "0600"

- name: create (and fix ownership of) monitor directory
  file:
    path: /var/lib/ceph/mon/{{ ceph.cluster_name }}-{{ monitor_name }}
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
    recurse: true

- name: set_fact for admin authtool
  set_fact:
    client_admin_ceph_authtool_cap:
      mon: allow *
      osd: allow *
      mds: allow
      mgr: allow *

- name: state ceph keyring_etc
  stat:
    path: /etc/ceph/ceph.client.admin.keyring
  register: keyring_etc

- name: create custom admin keyring
  ceph_key:
    name: client.admin
    state: present
    secret: "{{ ceph.monitor_keyring }}"
    auid: 0
    caps: "{{ client_admin_ceph_authtool_cap }}"
    import_key: False
    cluster: "{{ ceph.cluster_name }}"
  register: keyring_etc_create
  when: keyring_etc.stat.exists == false

- name: set ownership of admin keyring
  file:
    path: /etc/ceph/{{ ceph.cluster_name }}.client.admin.keyring
    state: file
    owner: 'ceph'
    group: 'ceph'
    mode: '0600'

- name: import admin keyring into mon keyring
  command: ceph-authtool /var/lib/ceph/tmp/{{ ceph.cluster_name }}.mon..keyring --import-keyring /etc/ceph/{{ ceph.cluster_name }}.client.admin.keyring
  when: keyring_tmp_create.changed or keyring_etc_create.changed

- name: check monitor directory is empty
  stat:
    path: /var/lib/ceph/mon/{{ ceph.cluster_name }}-{{ monitor_name }}/keyring
  register: monitor_dir

- name: ceph monitor mkfs with keyring
  command: ceph-mon --cluster {{ ceph.cluster_name }} --setuser ceph --setgroup ceph --mkfs -i {{ monitor_name }} --fsid {{ ceph.fsid }} --keyring /var/lib/ceph/tmp/{{ ceph.cluster_name }}.mon..keyring
  when: (keyring_tmp_create.changed or keyring_etc_create.changed) and monitor_dir.stat.exists == false

- name: start the monitor service
  service:
    name: ceph-mon@{{ monitor_name }}
    state: restarted
    enabled: yes
  when: (keyring_tmp_create.changed or keyring_etc_create.changed) and monitor_dir.stat.exists == false
